language: go

go:
  - 1.6
  - 1.7.x
  - 1.8.x
  - master

os:
 - linux
 - osx

install:
 - go get -t -v ./...

script:
 - "(go version | grep -q 1.4) || go tool vet -all ."
 - go install ./...
 - go test -v -race ./...
